build, scan and test

diff --git a/.github/workflows/ci_workflow_develop.yml b/.github/workflows/ci_workflow_develop.yml
--- a/.github/workflows/ci_workflow_develop.yml
+++ b/.github/workflows/ci_workflow_develop.yml
@@ -3,36 +3,36 @@ name: CI Workflow Develop Branch
 on:
   push:
     branches:
-      - develop               # Triggers. Gitaction will trigger when i git push develop branch
+      - develop               # Triggers. Gitaction will trigger when i git push develop branch only
 
 jobs:
   
   build:
-    runs-on: ${{ matrix.os }} #ensuring our projects can be build on all three kind of OS
+    runs-on: ${{ matrix.os }}
     strategy:
       matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
     steps:
-      - uses: actions/checkout@v3 #checks out github repo so that any files in my repo, such as dockerfile or configuration files are accessible
+      - uses: actions/checkout@v4
       - name: Set up JDK 17
-        uses: actions/setup-java@v3
+        uses: actions/setup-java@v4
         with:
           java-version: '17'
-          distribution: 'temurin' # Recommended distribution
+          distribution: 'temurin'
           cache: maven
       - name: Install Dependencies (Maven)
-        run: mvn -B clean install -DskipTests # -B for batch mode in mvn command. prevents interactive prompts in Maven, which can cause workflow to hang.
-      - name: Upload Artifacts (if needed) #crucial for multi OS build - saving the build outputs (JARs, etc) so that subsequents jobs (like testing and deploy) can use
+        run: mvn -B clean install -DskipTests
+      - name: Upload Artifacts (if needed)
         if: always() # Always run this step, even if previous steps fail
         uses: actions/upload-artifact@v4
         with:
-          name: target-${{ matrix.os }} # creating distinct artifact names (e.g. target-ubuntu-latest, target-marcos-latest). preventin overwriting artifacts
-          path: target/*.jar # Or the specific artifacts you need
-          retention-days: 1 # How long to keep the artifacts
+          name: target-${{ matrix.os }}
+          path: target/*.jar
+          retention-days: 1
 
   dependencies_scan:
-    runs-on: ubuntu-latest # No point scanning all three os cause this is about scanning our project
-    needs: build # Depends on the build job
+    runs-on: ubuntu-latest
+    needs: build
     steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 17
@@ -40,17 +40,17 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
-          cache: maven # Optional, but recommended
+          cache: maven
       - name: Install Snyk CLI
         uses: snyk/actions/setup@master
       - name: Run Snyk Vulnerability Scan (Dependencies Only)
-        env: # Define environment variables here
-          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # Use GitHub secrets
-        run: snyk test --file=pom.xml --severity-threshold=high || echo "Issues detected but not failing the build"  # Scan pom.xml for dependencies
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        run: snyk test --file=pom.xml --severity-threshold=high || echo "Issues detected but not failing the build"
 
   code_scan:
-    runs-on: ubuntu-latest # Similar to dependencies test - No point scanning all three os cause this is about scanning our project codes
-    needs: build # Depends on the build job
+    runs-on: ubuntu-latest
+    needs: build
     steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 17
@@ -58,9 +58,9 @@ jobs:
         with:
           java-version: '17'
           distribution: 'temurin'
-          cache: maven # Optional, but recommended
+          cache: maven
       - name: Install Snyk CLI
-        run: npm install -g snyk # Install snyk cli using npm
+        uses: snyk/actions/setup@master
       - name: Run Snyk Code Vulnerability Scan
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
@@ -70,7 +70,7 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest] #windows fails this test. need to look into this
+        os: [ubuntu-latest, macos-latest]
     needs: code_scan
     steps:
       - uses: actions/checkout@v3
@@ -78,14 +78,14 @@ jobs:
         uses: actions/setup-java@v3
         with:
           java-version: '17'
-          distribution: 'temurin' # Recommended distribution
+          distribution: 'temurin'
           cache: maven
-      - name: Download Artifacts #downloading the artifacts that was saved in build
+      - name: Download Artifacts
         uses: actions/download-artifact@v4
         with:
           name: target-${{ matrix.os }}
-          path: target # Download the contents into the 'target' directory
-      - name: Run Three Tests (Maven)
+          path: target
+      - name: Run Three Tests
         run: |
           export TEST_CLASSES="sg.edu.ntu.split_and_share.service.UserServiceImplTest,sg.edu.ntu.split_and_share.service.ExpenseServiceImplTest,sg.edu.ntu.split_and_share.controller.ExpenseControllerTest"
           mvn test -Dtest="$TEST_CLASSES"
